Repository LifePoop/LifePoop_iOS, pull requests merged in 2023-12, with the labels that each got.

#177 회원가입 처리 수정
  Projects/Core/CoreEntity/Sources/AgreementCondition.swift
  Projects/Core/CoreEntity/Sources/SignupInput.swift
  Projects/DesignSystem/Sources/Component/ConditionalTextField/ConditionalTextField.swift
  Projects/Features/FeatureLogin/FeatureLoginPresentation/Sources/SignupScene/ConditionSelectionCell/ConditionSelectionView.swift
  Projects/Features/FeatureLogin/FeatureLoginPresentation/Sources/SignupScene/SignupViewController.swift
  Projects/Features/FeatureLogin/FeatureLoginPresentation/Sources/SignupScene/SignupViewModel.swift
  Projects/Features/FeatureLogin/FeatureLoginRepository/Sources/DefaultSignupRepository.swift
  Projects/Features/FeatureLogin/FeatureLoginUseCase/Sources/DefaultSignupUseCase.swift
  Projects/Features/FeatureLogin/FeatureLoginUseCase/Sources/Interface/SignupUseCase.swift
  Projects/Logger/Sources/Rx+log.swift
Labels: 💡feat, ✂️refactor, Jed

#179 변 횟수가 동일할 경우, 지정된 순서로 나타나도록 수정
  Projects/DesignSystem/Sources/Component/UIView/EmptyStoolCharacterView.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendListViewController/FriendListViewController.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinator/Sources/DefaultHomeCoordinator.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinatorInterface/Sources/HomeCoordinatorAction.swift
  Projects/Features/FeatureReport/FeatureReportPresentation/Sources/ReportView/ReportTotalColorView.swift
  Projects/Features/FeatureReport/FeatureReportPresentation/Sources/ReportView/ReportTotalShapeView.swift
  Projects/Features/FeatureReport/FeatureReportPresentation/Sources/ReportViewController.swift
  Projects/Features/FeatureReport/FeatureReportPresentation/Sources/ReportViewModel.swift
  Projects/Utils/Resources/Localizable.strings
Labels: ✂️refactor, Mase

#180 앱 시작시 화면이 깜빡거리는 현상 해결
  Projects/App/Sources/AppCoordinator/DefaultAppCoordinator.swift
  Projects/Features/FeatureLogin/FeatureLoginCoordinator/Sources/DefaultLoginCoordinator.swift
Labels: 🛠fix, Mase

#184 시뮬레이터에서 간헐적으로 스레드 에러 발생하는 현상 해결
  Projects/Features/FeatureLogin/FeatureLoginCoordinator/Sources/DefaultLoginCoordinator.swift
Labels: 🛠fix, Mase

#185 탈퇴하기 요청 후 응답 오기 전까지 화면 터치 막기 처리
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/SettingViewController.swift
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/SettingViewModel.swift
  Projects/Utils/Sources/Extension/UIViewController+blockScreen.swift
Labels: 💡feat, Jed

#188 회원가입 시 생년월일값이 빈 값일 때 nil 리턴하도록 수정
  Projects/Features/FeatureLogin/FeatureLoginUseCase/Sources/DefaultSignupUseCase.swift
Labels: 🛠fix, 💡feat

#190 회원가입시 생년월일 입력 관련 버그 수정
  Projects/Features/FeatureLogin/FeatureLoginPresentation/Sources/SignupScene/SignupViewModel.swift
  Projects/Features/FeatureLogin/FeatureLoginUseCase/Sources/DefaultSignupUseCase.swift
Labels: 🛠fix, Mase
