Repository LifePoop/LifePoop_iOS, pull requests merged in 2023-11, with the labels that each got.

#134 앱 버전 업데이트 후 소셜 로그인 에러, 카카오 로그인 후 탈퇴 시 애플 팝업 창 뜨는 이슈 해결
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/SettingViewModel.swift
  Projects/Shared/SharedRepository/Sources/DefaultKeyChainRepository.swift
Labels: 🛠fix, Jed

#135 초대 코드 입력 로직 어색한 부분 수정
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/InvitationCodeViewController/InvitationCodeViewModel.swift
  Projects/Features/FeatureFriendList/FeatureFriendListUseCase/Sources/DefaultFriendListUseCase.swift
  Projects/Features/FeatureFriendList/FeatureFriendListUseCase/Sources/Interface/FriendListUseCase.swift
Labels: 🛠fix, Jed

#137 사용자 정보 UserDefaults에 저장하는 처리, 앱 기동 후 로그인 처리 미흡한 부분 수정
  Projects/Features/FeatureLogin/FeatureLoginUseCase/Sources/DefaultLoginUseCase.swift
  Projects/Shared/SharedRepository/Sources/DefaultKeyChainRepository.swift
  Projects/Shared/SharedUseCase/Sources/DefaultUserInfoUseCase.swift
  Projects/Utils/Sources/UserDefaults/UserDefaultsKeys.swift
Labels: 🛠fix, 💡feat, Jed

#138 프로필 캐릭터 수정 기능 API 연동하여 완성
  Projects/App/Sources/SceneDelegate.swift
  Projects/Core/CoreEntity/Sources/StoolLogEntity.swift
  Projects/Core/CoreNetworkService/Sources/DTO/StoolLogDTO.swift
  Projects/Core/CoreNetworkService/Sources/DataMapper/StoolLogDTOMapper.swift
  Projects/Core/CoreNetworkService/Sources/DataMapper/StoolLogEntityMapper.swift
  Projects/Core/CoreNetworkService/Sources/DataMapper/UserProfileDTOMapper.swift
  Projects/Core/CoreNetworkService/Sources/Target/LifePoopLocalTarget.swift
  Projects/DesignSystem/Sources/Component/UIButton/LifePoopButton.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendListViewController/FriendListViewModel.swift
  Projects/Features/FeatureHome/FeatureHomeUseCase/Sources/DefaultHomeUseCase.swift
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/ProfileEdit/ProfileCharacterEditViewModel.swift
  Projects/Features/FeatureSetting/FeatureSettingUseCase/Sources/DefaultProfileEditUseCase.swift
  Projects/Features/FeatureSetting/FeatureSettingUseCase/Sources/Interface/ProfileEditUseCase.swift
  Projects/Features/FeatureSetting/FeatureSettingUseCase/Sources/MockProfileEditUseCase.swift
  Projects/Features/FeatureStoolLog/FeatureStoolLogPresentation/Sources/Views/SatisfactionDetail/SatisfactionDetailViewModel.swift
  Projects/Shared/SharedRepository/Sources/DefaultUserInfoRepository.swift
  Projects/Shared/SharedRepository/Sources/DefaultUserProfileEditRepository.swift
  Projects/Shared/SharedUseCase/Sources/DefaultNicknameUseCase.swift
  Projects/Shared/SharedUseCase/Sources/DefaultStoryFeedUseCase.swift
  Projects/Shared/SharedUseCase/Sources/DefaultUserProfileEditUseCase.swift
  Projects/Shared/SharedUseCase/Sources/Interface/NicknameUseCase.swift
  Projects/Shared/SharedUseCase/Sources/Interface/UserProfileEditUseCase.swift
  Projects/Shared/SharedUseCase/Sources/RepositoryInterface/UserProfileEditRepository.swift
  Projects/Shared/SharedUseCase/Sources/StoryFeedUseCase.swift
Labels: 🛠fix, 💡feat, Mase

#140 친구 목록에서 볼 수 있는 친구의 변기록 화면 완성
  Projects/DesignSystem/Sources/Component/UICollectionView/FriendStoolLogCollectionViewSectionLayout.swift
  Projects/DesignSystem/Sources/Component/UIView/CheeringFriendProfileCharacterView.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendStoolLogViewController/FriendStoolLogCollectionView/FriendStoolLogCollectionViewDiffableDataSource.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendStoolLogViewController/FriendStoolLogCollectionView/FriendStoolLogHeaderView.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendStoolLogViewController/FriendStoolLogCollectionView/FriendStoolLogHeaderViewModel.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendStoolLogViewController/FriendStoolLogViewController.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendStoolLogViewController/FriendStoolLogViewModel.swift
  Projects/Utils/Resources/Localizable.strings
Labels: 💡feat, Mase

#142 FriendEntityMapper에서 FriendEntity에 대한 rawValue 인덱싱을 올바르게 수정
  Projects/Core/CoreNetworkService/Sources/DataMapper/FriendEntityMapper.swift
Labels: 🛠fix, Mase

#145 소셜 로그인 후 홈 화면으로 전환될 때 홈 상단 네비게이션 바가 보이지 않는 문제 해결
  Projects/App/Sources/AppCoordinator/DefaultAppCoordinator.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinator/Project.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinator/Sources/DefaultHomeCoordinator.swift
  Projects/Features/FeatureLogin/FeatureLoginCoordinator/Sources/DefaultLoginCoordinator.swift
  Projects/Features/FeatureReport/FeatureReportCoordinator/Sources/DefaultReportCoordinator.swift
  Projects/Features/FeatureReport/FeatureReportPresentation/Project.swift
  Projects/Features/FeatureReport/FeatureReportPresentation/Sources/ReportViewModel.swift
  Projects/Features/FeatureSetting/FeatureSettingCoordinator/Sources/DefaultSettingCoordinator.swift
Labels: 🛠fix, Mase

#152 친구 초대하기 경고 라벨 및 오류 토스트 색상 UI 수정
  Projects/Core/CoreEntity/Sources/InvitationCodeInput.swift
  Projects/DesignSystem/Resources/Color.xcassets/Poo_Pink.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/toast_failure.colorset/Contents.json
  Projects/DesignSystem/Sources/Component/UILabel/ToastLabel.swift
  Projects/DesignSystem/Sources/Component/UIView/LifePoopTextFieldAlertView.swift
  Projects/Features/FeatureFriendList/FeatureFriendListCoordinator/Sources/DefaultFriendListCoordinator.swift
  Projects/Features/FeatureFriendList/FeatureFriendListCoordinatorInterface/Sources/FriendListCoordinateAction.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendInvitationViewController/FriendInvitationViewModel.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendListViewController/FriendListViewController.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendListViewController/FriendListViewModel.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/InvitationCodeViewController/InvitationCodeViewController.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/InvitationCodeViewController/InvitationCodeViewModel.swift
  Projects/Features/FeatureFriendList/FeatureFriendListRepository/Sources/DefaultFriendListRepository.swift
  Projects/Features/FeatureFriendList/FeatureFriendListUseCase/Sources/DefaultFriendListUseCase.swift
  Projects/Features/FeatureFriendList/FeatureFriendListUseCase/Sources/Interface/FriendListUseCase.swift
  Projects/Features/FeatureFriendList/FeatureFriendListUseCase/Sources/RepositoryInterface/FriendListRepository.swift
  Projects/Utils/Resources/Localizable.strings
  Projects/Utils/Sources/Enum/ToastMessage+kind.swift
  Projects/Utils/Sources/Enum/ToastMessage.swift
Labels: 💡feat

#154 스토리 화면 최초 진입 시 응원 여부 확인하는 처리 추가
  Projects/Core/CoreEntity/Sources/StoryFeedEntity.swift
  Projects/Core/CoreNetworkService/Sources/DTO/UserProfileDTO.swift
  Projects/Core/CoreNetworkService/Sources/DataMapper/StoryFeedEntityMapper.swift
  Projects/Core/CoreNetworkService/Sources/Target/LifePoopLocalTarget.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinator/Sources/DefaultHomeCoordinator.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinatorInterface/Sources/HomeCoordinatorAction.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/FriendStoolStoryScene/FriendStoolStoryViewController.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/FriendStoolStoryScene/FriendStoolStoryViewModel.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/StoolLogCollectionView/StoolLogHeaderViewModel.swift
Labels: 💡feat

#156 CI 과정 중 Testflight 배포에 단계에서 발생하는 에러 수정
  Projects/Features/FeatureHome/FeatureHomeRepository/Project.swift
  Projects/Features/FeatureLogin/FeatureLoginRepository/Project.swift
  Projects/Features/FeatureStoolLog/FeatureStoolLogRepository/Project.swift
Labels: 🛠fix, Mase, ⚙️chore

#157 힘주기 요청 후 버튼 비활성화 처리 및 홈화면 헤더 상태 변경
  Projects/Core/CoreEntity/Sources/UserProfileEntity.swift
  Projects/Core/CoreNetworkService/Sources/DTO/UserProfileDTO.swift
  Projects/Core/CoreNetworkService/Sources/DataMapper/CheeringInfoEntityMapper.swift
  Projects/Core/CoreNetworkService/Sources/DataMapper/StoryFeedEntityMapper.swift
  Projects/Core/CoreNetworkService/Sources/DataMapper/UserProfileDTOMapper.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinator/Sources/DefaultHomeCoordinator.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinatorInterface/Sources/HomeCoordinatorAction.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/FriendStoolStoryScene/FriendStoolStoryViewModel.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/StoolLogCollectionView/StoolLogHeaderViewModel.swift
  Projects/Features/FeatureSetting/FeatureSettingUseCase/Sources/DefaultProfileEditUseCase.swift
  Projects/Utils/Sources/NotificationCenter/NotificationName.swift
Labels: 💡feat, Jed

#158 힘주기 요청 시 진동 제거하고 햅틱효과로 수정
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/FriendStoolStoryScene/FriendStoolStoryViewController.swift
Labels: 🛠fix

#163 가로모드 막기 처리
  Projects/App/Sources/AppDelegate.swift
Labels: 💡feat, Jed

#170 의견 보내기 URL을 사파리 앱에서 열도록 변경
  Projects/DesignSystem/Sources/Component/UIViewController/LifePoopWebViewController.swift
  Projects/Features/FeatureSetting/FeatureSettingCoordinator/Sources/DefaultSettingCoordinator.swift
Labels: ✂️refactor, Mase

#169 친구 추가 성공 후 홈 화면으로 돌아갈 시, 별도의 리프레시 없어도 갱신된 스토리 목록을 보여주도록 변경
  Projects/Features/FeatureFriendList/FeatureFriendListCoordinator/Sources/DefaultFriendListCoordinator.swift
  Projects/Features/FeatureFriendList/FeatureFriendListCoordinatorInterface/Sources/FriendListCoordinateAction.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendListViewController/FriendListViewModel.swift
  Projects/Features/FeatureFriendList/FeatureFriendListUseCase/Sources/DefaultFriendListUseCase.swift
  Projects/Features/FeatureFriendList/FeatureFriendListUseCase/Sources/Interface/FriendListUseCase.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinator/Sources/DefaultHomeCoordinator.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinatorInterface/Sources/HomeCoordinatorAction.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/HomeViewController.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/HomeViewModel.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/StoolLogCollectionView/StoolLogHeaderViewModel.swift
  Projects/Utils/Resources/Localizable.strings
  Projects/Utils/Sources/Enum/ToastMessage+kind.swift
  Projects/Utils/Sources/Enum/ToastMessage.swift
Labels: 💡feat, ✂️refactor, Mase

#159 로그인 코드 리팩토링, 일부 UX 개선
  Projects/DesignSystem/Sources/Component/UIButton/LifePoopButton.swift
  Projects/DesignSystem/Sources/Component/UIButton/LoginButton.swift
  Projects/Features/FeatureLogin/FeatureLoginCoordinator/Sources/DefaultLoginCoordinator.swift
  Projects/Features/FeatureLogin/FeatureLoginCoordinatorInterface/Sources/LoginCoordinateAction.swift
  Projects/Features/FeatureLogin/FeatureLoginPresentation/Sources/LoginScene/LoginViewController.swift
  Projects/Features/FeatureLogin/FeatureLoginPresentation/Sources/LoginScene/LoginViewModel.swift
  Projects/Features/FeatureLogin/FeatureLoginRepository/Sources/DefaultLoginRepository.swift
  Projects/Features/FeatureLogin/FeatureLoginUseCase/Sources/DefaultLoginUseCase.swift
  Projects/Features/FeatureLogin/FeatureLoginUseCase/Sources/Interface/LoginUseCase.swift
  Projects/Features/FeatureLogin/FeatureLoginUseCase/Sources/LoginError.swift
  Projects/Features/FeatureLogin/FeatureLoginUseCase/Sources/RepositoryInterface/LoginRepository.swift
  Projects/Logger/Sources/Rx+log.swift
  Projects/Shared/SharedUseCase/Sources/DefaultUserInfoUseCase.swift
  Projects/Utils/Resources/Localizable.strings
  Projects/Utils/Sources/Extension/UIViewController+showSystemAlert.swift
Labels: 🛠fix, 💡feat, ✂️refactor, Jed

#161 로그아웃, 탈퇴 코드 리팩토링, UX 개선
  Projects/Core/CoreEntity/Sources/UserAuthInfoEntity.swift
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/SettingViewController.swift
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/SettingViewModel.swift
  Projects/Shared/SharedUseCase/Sources/DefaultUserInfoUseCase.swift
  Projects/Shared/SharedUseCase/Sources/Interface/UserInfoUseCase.swift
Labels: 🛠fix, ✂️refactor, Jed

#172 초대 코드 입력 관련 UI 수정
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/FriendListViewController/FriendListViewController.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/InvitationCodeViewController/InvitationCodeViewController.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/InvitationCodeViewController/InvitationCodeViewModel.swift
  Projects/Utils/Sources/Enum/ToastMessage.swift
Labels: 🛠fix, Jed

#173 오픈소스 라이선스 표기 추가
  Projects/App/Resources/Settings.bundle/Root.plist
  Projects/App/Resources/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  Projects/App/Resources/Settings.bundle/com.mono0926.LicensePlist.plist
  Projects/App/Resources/Settings.bundle/com.mono0926.LicensePlist/Alamofire.plist
  Projects/App/Resources/Settings.bundle/com.mono0926.LicensePlist/RxSwift.plist
  Projects/App/Resources/Settings.bundle/com.mono0926.LicensePlist/SnapKit.plist
  Projects/App/Resources/Settings.bundle/com.mono0926.LicensePlist/kakao-ios-sdk.plist
  Projects/App/Resources/Settings.bundle/com.mono0926.LicensePlist/lottie-ios.plist
  Projects/App/Resources/Settings.bundle/en.lproj/Root.strings
  com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist.latest_result.txt
  com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist.plist
  com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/Alamofire.plist
  com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/RxSwift.plist
  com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/SnapKit.plist
  com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/kakao-ios-sdk.plist
  com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/lottie-ios.plist
Labels: Mase, ⚙️chore
