Repository LifePoop/LifePoop_iOS, pull requests merged in 2023-07, with the labels that each got.

#97 Tuist Manifests 파일 수정 및 entitlements 코드 설정
  Projects/App/Project.swift
  Tuist/ProjectDescriptionHelpers/Path+entitlements.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: Mase, ⚙️chore

#101 LifePoopButton이 비활성화 상태일 때 loading indicator와 title이 함께 나타나는 문제 해결
  Projects/DesignSystem/Sources/Component/UIButton/LifePoopButton.swift
  Projects/DesignSystem/Sources/Extension/String+nsAttributedString.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/FriendStoolStoryScene/FriendStoolStoryViewController.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/HomeViewController.swift
  Projects/Features/FeatureLogin/FeatureLoginPresentation/Sources/SignupScene/SignupViewController.swift
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/Feedback/FeedbackViewController.swift
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/ProfileEdit/ProfileEditViewController.swift
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/Withdrawal/WithdrawalViewController.swift
  Projects/Features/FeatureStoolLog/FeatureStoolLogPresentation/Sources/Views/SatisfactionDetail/SatisfactionDetailViewController.swift
Labels: 🛠fix, Mase

#99 Fastlane을 통한 빌드 배포 과정 자동화
  .gitignore
  Gemfile
  Gemfile.lock
  Projects/App/Project.swift
  Projects/App/xcconfigs/App.base.xcconfig
  Projects/App/xcconfigs/App.debug.xcconfig
  Projects/App/xcconfigs/App.release.xcconfig
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
Labels: Mase, ⚙️chore

#94 스토리 화면 UI 구현
  .swiftlint.yml
  Projects/Core/CoreEntity/Sources/StoolLogEntity.swift
  Projects/Core/CoreEntity/Sources/StoolStoryLogEntity.swift
  Projects/DesignSystem/Resources/Color.xcassets/gray_story_background.colorset/Contents.json
  Projects/DesignSystem/Resources/Image.xcassets/btn_close.imageset/Contents.json
  Projects/DesignSystem/Resources/Image.xcassets/btn_close.imageset/btn_close.png
  Projects/DesignSystem/Resources/Image.xcassets/btn_close.imageset/btn_close@2x.png
  Projects/DesignSystem/Resources/Image.xcassets/btn_close.imageset/btn_close@3x.png
  Projects/DesignSystem/Sources/Component/SegmentedProgressView/Segment.swift
  Projects/DesignSystem/Sources/Component/SegmentedProgressView/SegmentedProgressView.swift
  Projects/DesignSystem/Sources/Component/UIButton/LifePoopButton.swift
  Projects/DesignSystem/Sources/Extension/String+nsAttributedString.swift
  Projects/DesignSystemReactive/Sources/SegmentedProgressView+Reactive.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinator/Sources/DefaultHomeCoordinator.swift
  Projects/Features/FeatureHome/FeatureHomeCoordinatorInterface/Sources/HomeCoordinatorAction.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/FriendStoolStoryScene/FriendStoolStoryViewController.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/FriendStoolStoryScene/FriendStoolStoryViewModel.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/HomeViewController.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/StoolLogCollectionView/StoolLogHeaderView.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/StoolLogCollectionView/StoolLogHeaderViewModel.swift
  Projects/Features/FeatureHome/FeatureHomeRepository/Sources/DefaultHomeRepository.swift
  Projects/Features/FeatureHome/FeatureHomeUseCase/Sources/DefaultHomeUseCase.swift
  Projects/Features/FeatureHome/FeatureHomeUseCase/Sources/Interface/HomeUseCase.swift
  Projects/Features/FeatureHome/FeatureHomeUseCase/Sources/RepositoryInterface/HomeRepository.swift
  Projects/Features/FeatureLogin/FeatureLoginPresentation/Sources/SignupScene/SignupViewController.swift
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/Feedback/FeedbackViewController.swift
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/ProfileEdit/ProfileEditViewController.swift
  Projects/Features/FeatureSetting/FeatureSettingPresentation/Sources/Withdrawal/WithdrawalViewController.swift
  Projects/Features/FeatureStoolLog/FeatureStoolLogPresentation/Sources/Views/SatisfactionDetail/SatisfactionDetailViewController.swift
  Projects/Utils/Resources/Localizable.strings
  Projects/Utils/Sources/Extension/RxSwift/Rx+viewDidLayoutSubviews.swift
Labels: 💡feat, Jed, ⚡️review_needed
