Repository LifePoop/LifePoop_iOS, pull requests merged in 2023-08, with the labels that each got.

#105 로그인, 회원가입 QA 반영
  Projects/DesignSystem/Resources/Color.xcassets/kakao_brown.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/kakao_yellow.colorset/Contents.json
  Projects/Features/FeatureLogin/FeatureLoginPresentation/Sources/LoginScene/LoginViewController.swift
Labels: ✂️refactor, Jed

#109 홈 화면 스토리 피드에서 '나'에 대한 피드 삭제
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/FriendListCollectionView/FriendListCollectionViewDiffableDataSource.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/HomeViewModel.swift
  Projects/Features/FeatureHome/FeatureHomePresentation/Sources/StoolLogCollectionView/StoolLogHeaderViewModel.swift
Labels: ✂️refactor, Mase

#107 초대 코드 입력 화면 QA 반영
  Projects/DesignSystem/Resources/Localizable.strings
  Projects/DesignSystem/Sources/Component/UIView/LifePoopAlertView.swift
  Projects/DesignSystem/Sources/Component/UIView/LifePoopTextFieldAlertView.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/InvitationCodeViewController/InvitationCodeViewController.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/InvitationCodeViewController/InvitationCodeViewModel.swift
Labels: 💡feat, ✂️refactor, Jed, ⚙️chore

#111 LifePoopAlertView의 show(in:) 메소드 수정
  Projects/DesignSystem/Sources/Component/UIView/LifePoopAlertView.swift
  Projects/Features/FeatureFriendList/FeatureFriendListPresentation/Sources/InvitationCodeViewController/InvitationCodeViewController.swift
Labels: ✂️refactor, Mase

#114 Github Actions를 이용하여 CI/CD 가상환경 구축
  .github/workflows/testflight.yml
  .gitignore
  Projects/App/Project.swift
  Projects/App/xcconfigs/App.base.xcconfig
  fastlane/Appfile
  fastlane/Fastfile
Labels: Mase, ⚙️chore
