Repository LifePoop/LifePoop_iOS, pull requests merged in 2024-01, with the labels that each got.

#192 사용자 정보 디코딩 할 때 생년월일, 성별 정보를 옵셔널로 수정
  Projects/Core/CoreEntity/Sources/GenderType.swift
  Projects/Core/CoreEntity/Sources/UserInfoEntity.swift
  Projects/Core/CoreNetworkService/Sources/DTO/UserInfoDTO.swift
  Projects/Shared/SharedRepository/Sources/DefaultUserInfoRepository.swift
  Projects/Shared/SharedUseCase/Sources/DefaultUserInfoUseCase.swift
Labels: 🛠fix, Jed

#194 카카오톡 앱 설치 안되있을 경우 브라우저 통해서 로그인하도록 수정
  Projects/Core/CoreAuthentication/Sources/AuthenticationError.swift
  Projects/Core/CoreAuthentication/Sources/Managers/ASAuthorizationControllerProxy.swift
  Projects/Core/CoreAuthentication/Sources/Managers/KakaoAuthManager.swift
  Projects/Features/FeatureLogin/FeatureLoginRepository/Sources/DefaultLoginRepository.swift
Labels: 🛠fix, ✂️refactor, Jed

#196 초대 문구에 앱스토어 링크 URL 추가
  Projects/Utils/Resources/Localizable.strings
Labels: 💡feat, Mase
